insert into drugs (generic_name,generic_name_normalized,drug_class,renal_dosing) values
('Metformin','metformin','biguanide','{"rules":[{"maxEgfr":30,"recommendation":"contraindicated"}]}'),
('Glimepiride','glimepiride','sulfonylurea','{"rules":[{"maxEgfr":30,"recommendation":"avoid"}]}'),
('Empagliflozin','empagliflozin','sglt2i','{"rules":[{"maxEgfr":20,"recommendation":"avoid"}]}'),
('Insulin Glargine','insulinglargine','insulin','{"rules":[{"note":"reduce as eGFR declines"}]}'),
('Atorvastatin','atorvastatin','statin','{}'),('Rosuvastatin','rosuvastatin','statin','{"rules":[{"maxEgfr":30,"recommendation":"start low"}]}'),
('Amlodipine','amlodipine','ccb','{}'),('Telmisartan','telmisartan','arb','{"rules":[{"note":"monitor potassium in CKD"}]}'),('Ramipril','ramipril','ace_inhibitor','{"rules":[{"maxEgfr":30,"recommendation":"reduce"}]}'),('Lisinopril','lisinopril','ace_inhibitor','{"rules":[{"maxEgfr":30,"recommendation":"reduce"}]}'),
('Furosemide','furosemide','loop_diuretic','{"rules":[{"note":"higher doses in CKD"}]}'),('Spironolactone','spironolactone','k_sparing_diuretic','{"rules":[{"maxEgfr":30,"recommendation":"avoid"}]}'),('Bisoprolol','bisoprolol','beta_blocker','{}'),('Carvedilol','carvedilol','beta_blocker','{}'),('Aspirin','aspirin','antiplatelet','{}'),('Clopidogrel','clopidogrel','antiplatelet','{}'),('Ticagrelor','ticagrelor','antiplatelet','{}'),('Warfarin','warfarin','vka','{"rules":[{"note":"monitor INR"}]}'),('Rivaroxaban','rivaroxaban','doac','{"rules":[{"maxEgfr":15,"recommendation":"avoid"},{"maxEgfr":49,"recommendation":"15mg"}]}'),('Apixaban','apixaban','doac','{"rules":[{"maxEgfr":25,"recommendation":"reduce"}]}'),
('Enoxaparin','enoxaparin','lmwh','{"rules":[{"maxEgfr":30,"recommendation":"once daily"}]}'),('Amoxicillin','amoxicillin','penicillin','{"rules":[{"maxEgfr":30,"recommendation":"reduce frequency"}]}'),('Amoxicillin-Clavulanate','amoxicillinclavulanate','penicillin','{"rules":[{"maxEgfr":30,"recommendation":"reduce frequency"}]}'),('Ampicillin','ampicillin','penicillin','{"rules":[{"maxEgfr":30,"recommendation":"reduce frequency"}]}'),('Clarithromycin','clarithromycin','macrolide','{"rules":[{"maxEgfr":30,"recommendation":"reduce 50%"}]}'),('Azithromycin','azithromycin','macrolide','{}'),('Levofloxacin','levofloxacin','fluoroquinolone','{"rules":[{"maxEgfr":50,"recommendation":"adjust"}]}'),('Ciprofloxacin','ciprofloxacin','fluoroquinolone','{"rules":[{"maxEgfr":30,"recommendation":"reduce 50%"}]}'),('Meropenem','meropenem','carbapenem','{"rules":[{"maxEgfr":26,"recommendation":"reduce"}]}'),('Ceftriaxone','ceftriaxone','cephalosporin_3rd','{}'),('Cefazolin','cefazolin','cephalosporin_1st','{"rules":[{"maxEgfr":35,"recommendation":"reduce"}]}'),('Nitrofurantoin','nitrofurantoin','nitrofuran','{"rules":[{"maxEgfr":30,"recommendation":"avoid"}]}'),('Co-trimoxazole','cotrimoxazole','sulfonamide','{"rules":[{"maxEgfr":15,"recommendation":"avoid"}]}'),('Gabapentin','gabapentin','gabapentinoid','{"rules":[{"maxEgfr":60,"recommendation":"reduce 50%"},{"maxEgfr":30,"recommendation":"100mg OD"}]}'),('Pregabalin','pregabalin','gabapentinoid','{"rules":[{"maxEgfr":60,"recommendation":"reduce"},{"maxEgfr":30,"recommendation":"reduce 75%"}]}'),('Escitalopram','escitalopram','ssri','{}'),('Fluoxetine','fluoxetine','ssri','{}'),('Duloxetine','duloxetine','snri','{"rules":[{"maxEgfr":30,"recommendation":"avoid"}]}'),('Tramadol','tramadol','opioid','{"rules":[{"maxEgfr":30,"recommendation":"reduce"}]}'),('Morphine','morphine','opioid','{"rules":[{"maxEgfr":30,"recommendation":"reduce"}]}'),('Fentanyl','fentanyl','opioid','{"rules":[{"note":"preferred in CKD"}]}'),('Paracetamol','paracetamol','analgesic','{}'),('Diclofenac','diclofenac','nsaid','{"rules":[{"note":"avoid in CKD"}]}'),('Ibuprofen','ibuprofen','nsaid','{"rules":[{"note":"avoid in CKD"}]}'),('Pantoprazole','pantoprazole','ppi','{}'),('Omeprazole','omeprazole','ppi','{}'),('Tamsulosin','tamsulosin','alpha_blocker','{}'),('Digoxin','digoxin','cardiac_glycoside','{"rules":[{"maxEgfr":30,"recommendation":"reduce and monitor"}]}'),('Phenytoin','phenytoin','anticonvulsant','{"rules":[{"note":"complex in CKD"}]}'),('Sodium Valproate','sodiumvalproate','anticonvulsant','{}');

insert into drug_interactions (drug_a,drug_b,severity,mechanism,clinical_effect,management) values
('Clarithromycin','Atorvastatin','SEVERE','CYP3A4 inhibition','rhabdomyolysis risk','use azithromycin alternative'),('Clarithromycin','Rosuvastatin','MODERATE','CYP effect','myopathy risk','monitor'),('Clarithromycin','Amlodipine','MODERATE','CYP3A4','hypotension','monitor BP'),('Clarithromycin','Warfarin','SEVERE','CYP','INR increase','avoid/monitor INR'),('Ciprofloxacin','Warfarin','MODERATE','CYP1A2','INR increase','monitor INR'),('Fluoxetine','Tramadol','SEVERE','serotonin excess','serotonin syndrome','avoid'),('Escitalopram','Tramadol','MODERATE','serotonin excess','toxicity risk','monitor'),('Diclofenac','Telmisartan','SEVERE','renal hemodynamic impact','AKI risk','avoid'),('Diclofenac','Ramipril','SEVERE','renal hemodynamic impact','AKI risk','avoid'),('Ibuprofen','Aspirin','MODERATE','platelet competition','reduced antiplatelet effect','avoid'),('Warfarin','Aspirin','SEVERE','additive anticoag','major bleed','avoid unless specialist'),('Spironolactone','Ramipril','MODERATE','potassium retention','hyperkalemia','monitor K'),('Spironolactone','Telmisartan','MODERATE','potassium retention','hyperkalemia','monitor K'),('Digoxin','Amiodarone','SEVERE','reduced digoxin clearance','digoxin toxicity','reduce digoxin'),('Metformin','Contrast dye','MODERATE','renal insult','lactic acidosis risk','hold metformin'),('Phenytoin','Sodium Valproate','MODERATE','metabolism changes','level instability','monitor levels'),('Duloxetine','Tramadol','SEVERE','serotonin excess','serotonin syndrome','avoid'),('Clopidogrel','Omeprazole','MODERATE','CYP2C19 inhibition','reduced antiplatelet effect','prefer pantoprazole'),('Clopidogrel','Pantoprazole','MINOR','weak CYP2C19 effect','minimal impact','acceptable'),('Rivaroxaban','Clarithromycin','SEVERE','P-gp/CYP3A4','bleeding','avoid'),('Apixaban','Clarithromycin','MODERATE','P-gp/CYP3A4','higher apixaban levels','dose/monitor'),('Simvastatin','Amlodipine','MODERATE','CYP3A4','myopathy risk','limit simvastatin dose'),('Methotrexate','Co-trimoxazole','SEVERE','antifolate synergy','pancytopenia','avoid'),('Carbamazepine','Clarithromycin','SEVERE','CYP3A4 inhibition','carbamazepine toxicity','avoid'),('Theophylline','Ciprofloxacin','SEVERE','CYP1A2 inhibition','seizure risk','avoid'),('Escitalopram','Ondansetron','MODERATE','QT prolongation','torsades risk','avoid/ECG'),('Metformin','Furosemide','MINOR','renal stress','lactic acidosis risk in CKD','monitor renal function'),('Morphine','Escitalopram','MINOR','CNS effects','sedation','monitor'),('Pregabalin','Morphine','MODERATE','CNS depression','respiratory depression','dose reduce'),('Lithium','Diclofenac','SEVERE','reduced lithium clearance','lithium toxicity','avoid');

insert into allergy_cross_reactivity (allergy_to,cross_reacts_with,cross_reactivity_pct,clinical_guidance) values
('penicillin','amoxicillin','100%','direct match'),('penicillin','ampicillin','100%','direct match'),('penicillin','cephalosporin_1st','1-2%','avoid if anaphylaxis'),('penicillin','cephalosporin_3rd','<0.5%','use caution'),('penicillin','carbapenem','<1%','generally safe'),('sulfonamide','co-trimoxazole','100%','same class'),('ace inhibitor','ace_inhibitor','100%','angioedema risk'),('ace inhibitor','arb','0%','safe'),('nsaid/aspirin','nsaid','variable','avoid all NSAIDs in AERD');
